enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

cli-source = "MorpheApp/morphe-desktop"
cli-version = "dev"

[YouTube-Extended]
enabled = true
app-name = "YouTube"
rv-brand = "ReVanced Extended"
build-mode = "both"
# version = "20.31.42"
patches-source = "anddea/revanced-patches"
patches-version = "dev"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkpure-dlurl = "com.google.android.youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Custom header for YouTube'"
# included-patches = "'Theme'" 

[YouTube-Music-Extended]
enabled = true
app-name = "YouTube Music"
rv-brand = "ReVanced Extended"
build-mode = "both"
arch = "both"
# version = "8.30.54"
patches-source = "anddea/revanced-patches"
patches-version = "dev"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkpure-dlurl = "com.google.android.apps.youtube.music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Custom header for YouTube Music'"
included-patches = "'Disable music video in album'" 

[YouTube-Morphe]
enabled = true
app-name = "YouTube"
rv-brand = "Morphe"
build-mode = "both"
# version = "20.21.37"
patches-source = "sashade8-ship-it/dual-vot-patches"
patches-version = "dev"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkpure-dlurl = "com.google.android.youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# excluded-patches = "'Custom branding' 'Custom header'"
# addon-patches-source = "sashade8-ship-it/morphe-patches-yavot"

[YouTube-Music-Morphe]
enabled = true
app-name = "YouTube Music"
rv-brand = "Morphe"
build-mode = "both"
arch = "both"
# version = "8.30.54"
patches-source = "MorpheApp/morphe-patches"
patches-version = "dev"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkpure-dlurl = "com.google.android.apps.youtube.music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# excluded-patches = "'Custom branding' 'Custom header'"